### ISSUE TITLE
"X years ago" is not rounding correctly

### ISSUE THREAD

**Issue by antn** [github/relative-time-element#270]
I noticed that something from Feb 2020 displayed as "5 years ago", when it is closer to 4 years if we are trying to round?

![Image](https://github.com/github/relative-time-element/assets/858504/99bf6850-ab59-4b80-a64f-8a3ed42a27d5)

**Comment by Gusted** [comment]
Some light investigation suggests that the problem is in `roundToSingleUnit` (`months` and `days` needs to be specified for it to reproduce) likely [around this logic](github.com/github/relative-time-element/blob/d0da95b8c69bd22b76781d50d6143f7427844380/src/duration.ts#L154-L168), there's no comment here so I'm not sure what this logic is supposed to do. Here's a concrete testcase that currently fails.

```diff
diff --git a/test/duration.ts b/test/duration.ts
index ef96d97..e6c6aaf 100644
--- a/test/duration.ts
+++ b/test/duration.ts
@@ -309,6 +309,7 @@ suite('duration', function () {
         },
       ],
       ['-P27D', '-P1M', {relativeTo: new Date('2023-02-28T00:00:00Z')}],
+      [{days: -15, months: -11}, '-P1Y', {relativeTo: new Date('2024-01-06T00:00:00')}],
     ])
     for (const [input, expected, opts] of roundTests) {
       test(`roundToSingleUnit(${input}) === ${expected}`, () => {
```

**Comment by martinburger** [comment]
I think I ran into a similar issue:

<img width="264" alt="image" src="https://github.com/github/relative-time-element/assets/954561/31cacb24-c406-48e1-bd11-a2ae0055a99d">

This screenshot has been taken from a Gitea instance. Gitea uses [relative-time-element](https://github.com/github/relative-time-element) to display, well, relative dates.

**Comment by santeriv** [comment]
Yeah seeing similar on 2024-01-15 (not yet 3 years, but it shows 4 years ) compared to real value 2021-02-02 . 
![image](https://github.com/github/relative-time-element/assets/170341/9d935bd3-102b-47f7-b23c-510d6689d5e1)

Did not make a test case of this..
