### ISSUE TITLE
Feb 29th showing as 'yesterday' on March 31

### ISSUE THREAD

**Issue by Esbylion** [github/relative-time-element#281]
Minimal reproduction:
```html
<html>
<body>
<relative-time datetime="2024-02-29 07:20:54.629275+00:00"></relative-time>
<script type="module" src="https://unpkg.com/@github/relative-time-element@latest/dist/bundle.js"></script>
</body>
</html>
```
Screenshot from 2024-03-31 at 6:03 PM, GMT +11
![Screenshot from 2024-03-31 18-03-43](https://github.com/github/relative-time-element/assets/33768843/0411b78e-aca2-4e60-8024-1836c435b2ae)

This appears the same on Firefox for Android, Firefox on Linux Mint, Firefox on Windows 10, and Edge on Windows 10.

**Comment by depoulo** [comment]
Oh yes! Saw that in production https://twitter.com/depoulo/status/1620703935186231302

**Comment by depoulo** [comment]
Might be related: https://twitter.com/depoulo/status/1620703935186231302

**Comment by silverwind** [comment]
Bug is also reproducible on GitHub currently:

<img width="425" alt="image" src="https://github.com/github/relative-time-element/assets/115237/f0fa08e6-8290-4a56-b2d5-bd9fa3a5a44c">

currently it's 2024-05-31T12:16:54.112Z

2024-05-01T12:32:52.000Z renders "30 days ago" which is ok
2024-05-01T05:33:40.000Z renders "now" but should be "31 days ago" or "a month ago"
2024-04-30T12:39:36.000Z renders "yesterday" but should be "32 days ago" or "a month ago"

It looks like all subsequent dates after the point where it breaks are off by 1 month.

**Comment by lilyinstarlight** [comment]
It happens because of JavaScript date math and the reliance on difference between `.getMonth()` calls after `.setMonth()` calls for relative time rounding, in this case when `duration.days === 0` and `duration.months === -1` and `relativeTo === new Date('2024-05-31')`

```
[I] lily@bina ~> node
Welcome to Node.js v22.2.0.
Type ".help" for more information.
> let date = new Date()
undefined
> date
2024-05-31T18:32:29.029Z
> date.getMonth()
4
> date.setMonth(3)
1714588349029
> date.getMonth()
4
> date
2024-05-01T18:32:29.029Z
>
```

I've got a patch cooked up to fix this anomaly by correcting "May 31 minus 1 month" to be equal to "April 30" rather than "May 1". I don't know if that is _semantically_ what is desired by this library, but I've never touched or used this library before really so I don't know very well what would be "expected" outputs

**Comment by lilyinstarlight** [comment]
I've opened #285 to fix this behavior

**Comment by GBirkel** [comment]
This is all over github right now.  April 30th in my repo renders as "yesterday".

If I'm reading this correctly, this is happening because "less than one month ago" is being considered the equivalent of "this month".  That shortcut equivalence is obviously flawed.  Tweaking the definition of "one month ago" is not the solution.  Making a better calculation for "this month" is.

I assume "this month" should be based on converting "now" into a timestamp with the same time zone as the given timestamp, and then asking for only the month value and comparing the two, yes?

**Comment by daz10000** [comment]
I think the true fix is to standardize the month to be 28 days consistently but in the interim this needs some serious test coverage.
It's May 31st and April 30th is yesterday..

![image](https://github.com/github/relative-time-element/assets/6342645/4cd18356-8ccd-46ec-9149-1f7f2dc930cc)

**Comment by GBirkel** [comment]
That would work. We could call the extra 13th month "Decemburary", and the one leftover day in the year could be called "bonus day", during which absolutely nothing works, so it's a worldwide holiday.  We could even tweak the length of "bonus day" to fix the whole leap-year problem!

**Comment by daz10000** [comment]
Month 13th could be nulluary or "Month Does Not Exist"

**Comment by depoulo** [comment]
If it worked for the [Eastman Kodak Company](https://en.wikipedia.org/wiki/Moses_B._Cotsworth), it could work for GitHub 🤷🏽
